company_name: "ITSSolutions"
company_domain: "itsolutions.me"

managed_by: "AAP-2.6"
inventory_source: "scm-git"

timezone: "Europe/Paris"

# Default SSH user for Linux hosts
ansible_user: "svc-ansible"

# Disable host key checking for SSH connections
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
