timezone: Europe/Paris

company_name: "ITSSolutions"

ntp_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"

dns_servers:
  - "10.0.0.10"
  - "10.0.0.11"

default_domain: "corp.itssolutions.me"

ansible_common_user: "ansible"

baseline_tags:
  - "managed_by_ansible"
  - "inventory_itssolutions"
