os_family: linux

ansible_connection: ssh
ansible_port: 22
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'


linux_packages_baseline:
  - curl
  - vim
  - rsyslog
  - chrony

linux_services_baseline:
  - chronyd
  - rsyslog

ssh_hardening:
  permit_root_login: false
  password_authentication: false
