os_family: windows

ansible_connection: winrm
ansible_port: 5985
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 60
ansible_winrm_read_timeout_sec: 90

windows_features_baseline:
  - "NET-Framework-Features"
  - "RSAT"

windows_services_baseline:
  - "W32Time"
  - "WinRM"
