ansible_connection: winrm
ansible_port: 5986
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore

# Optionnel si timeouts n√©cessaires
# ansible_winrm_operation_timeout_sec: 60
# ansible_winrm_read_timeout_sec: 90
