ansible_host: 10.10.0.6
ansible_connection: winrm
ansible_port: 5985
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore

env: dev
department: finance
os_family: windows
host_role: app
criticality: low
